### ISSUE TITLE
No ejecutable en Windows 8.1

### ISSUE THREAD

**Issue by hernandemczuk** [SistemasAgiles/pyfactura#5]
La instalación se completó satisfactoriamente pero al momento de abrir el programa advierte la siguiente excepción:

![issue](https://cloud.githubusercontent.com/assets/4275069/9563223/92541418-4e53-11e5-9429-4511824de27e.png)

EDIT: No es compatible con arquitecturas de 64 bits. Mala mía

**Comment by reingart** [comment]
Debería ser compatible con 64 bits o sino se puede recompilar.

El error te dice que no puede abrir la base de datos interna, posiblemente porque el directorio de instalación no tiene los permisos de modificación.
Por ej, si se instaló en Program Files (Archivos de Porgrama), se debe ir a la solapa de segurirdad en las propiedades de la carpeta pyfactura, y agregar el permiso de modificación al usuario:

![win81_propiedaeds_seguridad](https://cloud.githubusercontent.com/assets/1041385/10702608/29688dc0-79a1-11e5-8081-c1936a702fea.png)

![win81_permisos_modif](https://cloud.githubusercontent.com/assets/1041385/10702602/23498dcc-79a1-11e5-83e1-5b3b79a8a179.png)
